FROM ruby:3.4.10-bookworm

MAINTAINER Sharetribe Team <team@sharetribe.com>

ENV REFRESHED_AT 2023-02-01

RUN apt-get update && apt-get dist-upgrade -y

# Prevent GPG from trying to bind on IPv6 address even if there are none
RUN mkdir ~/.gnupg \
  && chmod 600 ~/.gnupg \
  && echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf

#
# Node (based on official docker node image)
#

# gpg keys listed at https://github.com/nodejs/node#release-team
RUN set -ex \
  && for key in \
    4ED778F539E3634C779C87C6D7062848A1AB005C \
    141F07595B7B3FFE74309A937405533BE57C7D57 \
    74F12602B6F1C4E913FAA37AD3A89613643B6201 \
    DD792F5973C6DE52C432CBDAC77ABFA00DDBF2B7 \
    61FC681DFB92A079F1685E77973F295594EC4689 \
    8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600 \
    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
    890C08DB8579162FEE0DF9DB8BEAB4DFCF555EF4 \
    C82FA3AE1CBEDC6BE46B9360C43CEC45C17AB93C \
    108F52B48DB57BB0CC439B2997B01419BD92F80A \
  ; do \
    gpg --batch --keyserver hkp://keys.openpgp.org --recv-keys "$key" || \
    gpg --batch --keyserver hkp://keyserver.ubuntu.com --recv-keys "$key" ; \
  done

ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_VERSION 18.16.0

# Detect architecture and download correct Node.js binary
RUN ARCH=$(dpkg --print-architecture) && \
    if [ "$ARCH" = "arm64" ]; then NODE_ARCH="arm64"; else NODE_ARCH="x64"; fi && \
    curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-$NODE_ARCH.tar.xz" \
    && tar -xJf "node-v$NODE_VERSION-linux-$NODE_ARCH.tar.xz" -C /usr/local --strip-components=1 \
    && rm "node-v$NODE_VERSION-linux-$NODE_ARCH.tar.xz" \
    && ln -s /usr/local/bin/node /usr/local/bin/nodejs

#
# Sharetribe Development
#

# Install:
# - nginx - used to serve maintenance mode page
# - libvips - image library
# - default-mysql-client - for rails db commands
RUN apt-get install -y nginx libvips default-mysql-client

# Install latest bundler
ENV BUNDLE_BIN=
RUN gem update --system 3.4.6

# Create app user and fix bundle permissions
RUN useradd -m -s /bin/bash app \
	&& mkdir /opt/app /opt/app/client /opt/app/log /opt/app/tmp \
	&& chown -R app:app /opt/app \
	&& chown -R app:app /usr/local/bundle

WORKDIR /opt/app

COPY --chown=app:app Gemfile Gemfile.lock /opt/app/

ENV RAILS_ENV=development
ENV BUNDLE_PATH=/usr/local/bundle

USER app

# Install gems (development group included)
RUN bundle config set --local without '' && \
    bundle install

COPY --chown=app:app package.json package-lock.json /opt/app/
COPY --chown=app:app client/package.json client/package-lock.json /opt/app/client/

ENV NODE_ENV=development
ENV NPM_CONFIG_LOGLEVEL=info

RUN npm ci --ignore-scripts && cd client && npm ci --ignore-scripts

COPY --chown=app:app . /opt/app

EXPOSE 3000

# Fix ownership of directories that need to be writable
USER root
RUN mkdir -p \
          app/assets/webpack \
          public/assets \
          public/webpack \
          tmp/pids \
          tmp/cache \
          log \
    && chown -R app:app \
       app/assets/javascripts \
       app/assets/webpack \
       client/app/ \
       public/assets \
       public/webpack \
       tmp \
       log
USER app

CMD ["bash", "-c", "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"]
